import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import createTheme from "@mui/material/styles/createTheme";
import ThemeProvider from "@mui/material/styles/ThemeProvider";
import theme from "./theme";
import ThemeRegistry from "./ThemeRegistry";
import CustomAppBar from "@/components/layout/CustomAppBar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body>
                <ThemeRegistry options={{key: "mui"}}>
                    <CustomAppBar />
                    <main>{children}</main>
                </ThemeRegistry>
            </body>
        </html>
    );
}
